language: go

go:
- 1.15
- 1.x
- master

jobs:
  allow_failures:
  - go: master

script:
  - go test -race -coverprofile=generator.cov -covermode=atomic ./generator
  - go test -race -coverprofile=parse.cov -covermode=atomic ./parse

after_script:
  - bash <(curl -s https://codecov.io/bash) -f '*.cov'
  