language: go

go:
- 1.15
- 1.x
- master

script:
  - go test -race -coverprofile=types.cov -covermode=atomic ./types
  - go test -race -coverprofile=config.cov -covermode=atomic ./config

after_script:
  - bash <(curl -s https://codecov.io/bash) -f '*.cov'
  