dist: focal

addons:
  postgresql: "14"
  apt:
    sources:
      - sourceline: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main
        key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    packages:
      - postgresql-14

language: go

go:
- 1.16
- 1.x
- master

jobs:
  allow_failures:
  - go: master

env:
  global:
  - PGHOST=/var/run/postgresql
  - PGPORT=5433
  - PGUSER=travis
  - PGDATABASE=testdata

before_script:
  - createdb

script:
  - go test -race -coverprofile=generator.cov -covermode=atomic ./generator
  - go test -race -coverprofile=parse.cov -covermode=atomic ./parse
  - go test -race -coverprofile=main.cov -covermode=atomic ./

after_script:
  - bash <(curl -s https://codecov.io/bash) -f '*.cov'
  